name: Build a Pelican Website
on:
  push:
    # This prevents the workflow from running automatically on a new branch
    # When creating a new site branch, please ensure that the push and checkout branches agree
    # and that the action/pelican destination value is updated accordingly
    branches: ['main']
    paths:
      - 'content/**'
      - 'pelicanconf.py'
      - '.asf.yaml'
  workflow_dispatch:
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # because we push to asf-site
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          # This must equal the push/branches list above, and be appropriate for the destination below
          ref: 'main'
      - uses: apache/infrastructure-actions/pelican@ed044141796eb8ad67581cf5f4210656ffa77daa
        with:
          # This must be appropriate for the branch being built
          destination: 'asf-site'
          gfm: 'true'
